In [2]:
import pandas as pd
import numpy as np
from skimage.transform import resize
import matplotlib.pyplot as plt 
import os,glob
import csv #matplotlib inline 
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from skimage.io import imread, imshow 
paths = [os.getcwd()+"/Desktop/Project/Images/Animals/Test/animals"]
arrays = {} 
for path in paths:
    for filename in glob.iglob(path + '**/*.jpg', recursive=True):
        photo = load_img(filename, target_size=(5, 5))
        updated_photo_array = img_to_array(photo).reshape(3, 5,5)          
        print(updated_photo_array)
        head, tail = os.path.split(filename)
        label=os.path.splitext(tail)[0]
        arrays[label] = (updated_photo_array[0],updated_photo_array[1],updated_photo_array[2]) 
        
        df=pd.DataFrame.from_dict(arrays)
        print(df)
        df.to_csv ('exportImage_Animals_Test_DF.csv')

[[[165. 169. 144. 134. 136.]
  [112. 178. 191. 171. 140.]
  [143. 126.  84.  86.  73.]
  [ 63.  76.  48. 115. 131.]
  [104. 100. 125. 147.  20.]]

 [[ 38.  24. 182. 184. 181.]
  [139.  92.  36. 162. 108.]
  [ 44.  87. 120. 137. 128.]
  [139. 131. 152. 138. 129.]
  [ 58.  39.   0. 123.  94.]]

 [[ 36. 129.  87.  11. 226.]
  [178.  93. 111. 117. 105.]
  [ 78.  90.  54.  45.  51.]
  [ 25.  69.  77.  56. 122.]
  [129.  98. 107. 108. 100.]]]
                                   35_shotopir_part1
0  [[165.0, 169.0, 144.0, 134.0, 136.0], [112.0, ...
1  [[38.0, 24.0, 182.0, 184.0, 181.0], [139.0, 92...
2  [[36.0, 129.0, 87.0, 11.0, 226.0], [178.0, 93....
[[[ 30.  30.  32.  25.  29.]
  [ 30. 210. 101.  62.  63.]
  [ 40.  34.  42.  27.  24.]
  [175. 151. 125. 186. 132.]
  [106. 118.  76.  64. 242.]]

 [[224. 202. 255. 251. 242.]
  [141. 100.  80. 165. 107.]
  [ 85. 176. 131. 112.  55.]
  [ 33.  22.  55.  21.   9.]
  [236. 208.  99.  97.  68.]]

 [[ 12. 157. 104.  88. 133.]
  [ 84.  69. 185. 179.  

2  [[0.0, 159.0, 128.0, 64.0, 147.0], [107.0, 0.0...  
[[[118.  81.  39. 167. 117.]
  [ 44. 148. 100.  54.  73.]
  [ 65.  26. 143. 108.  78.]
  [ 96.  56.  31.  90.  48.]
  [ 23. 178. 142.  90. 203.]]

 [[133.  35. 153. 131.  84.]
  [117.  85.  46. 121. 127.]
  [ 81. 214. 166.  81.  85.]
  [ 57.   0. 200. 169. 105.]
  [184. 120.  59.  76.  39.]]

 [[  0. 216. 177. 102. 156.]
  [104.  64. 208. 188. 102.]
  [ 69.  46.  14. 100.  73.]
  [ 20.  67.  36.   0.  68.]
  [ 58.   7.  98.  56.  34.]]]
                                   35_shotopir_part1  \
0  [[165.0, 169.0, 144.0, 134.0, 136.0], [112.0, ...   
1  [[38.0, 24.0, 182.0, 184.0, 181.0], [139.0, 92...   
2  [[36.0, 129.0, 87.0, 11.0, 226.0], [178.0, 93....   

                                   35_shotopir_part5  \
0  [[30.0, 30.0, 32.0, 25.0, 29.0], [30.0, 210.0,...   
1  [[224.0, 202.0, 255.0, 251.0, 242.0], [141.0, ...   
2  [[12.0, 157.0, 104.0, 88.0, 133.0], [84.0, 69....   

                                      34_animalworld  

2  [[36.0, 83.0, 26.0, 7.0, 45.0], [28.0, 34.0, 6...  
[[[162. 138. 104.  38.  39.]
  [ 31.  43.  48.  52.  53.]
  [ 54.  23.  72.  75.  48.]
  [189. 189. 161. 121. 121.]
  [ 95.  30.  70. 105. 154.]]

 [[143.  81. 204. 164. 129.]
  [147. 149. 125. 115.  76.]
  [ 45.  26.  39.  83.  79.]
  [ 33.   9.  27.  45.  55.]
  [116. 105. 101. 138. 121.]]

 [[ 91.  76.  70.  36. 171.]
  [170. 152. 108.  57.  64.]
  [230. 204. 117.  29.  16.]
  [  0.  61.  27.  15. 103.]
  [ 76.  46. 193. 196. 187.]]]
                                   35_shotopir_part1  \
0  [[165.0, 169.0, 144.0, 134.0, 136.0], [112.0, ...   
1  [[38.0, 24.0, 182.0, 184.0, 181.0], [139.0, 92...   
2  [[36.0, 129.0, 87.0, 11.0, 226.0], [178.0, 93....   

                                   35_shotopir_part5  \
0  [[30.0, 30.0, 32.0, 25.0, 29.0], [30.0, 210.0,...   
1  [[224.0, 202.0, 255.0, 251.0, 242.0], [141.0, ...   
2  [[12.0, 157.0, 104.0, 88.0, 133.0], [84.0, 69....   

                                      34_animalworld  