In [2]:
import pandas as pd
import numpy as np
from skimage.transform import resize
import matplotlib.pyplot as plt 
import os,glob
import csv #matplotlib inline 
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from skimage.io import imread, imshow 
paths = [os.getcwd()+"/Desktop/Project/Images/Trees/Test/trees"]
arrays = {} 
for path in paths:
    for filename in glob.iglob(path + '**/*.jpg', recursive=True):
        photo = load_img(filename, target_size=(5, 5))
        updated_photo_array = img_to_array(photo).reshape(3, 5,5)          
        print(updated_photo_array)
        head, tail = os.path.split(filename)
        label=os.path.splitext(tail)[0]
        arrays[label] = (updated_photo_array[0],updated_photo_array[1],updated_photo_array[2]) 
        
        df=pd.DataFrame.from_dict(arrays)
        print(df)
        df.to_csv ('exportImage_Trees_Test_DF.csv')

[[[158. 147. 127. 210. 195.]
  [188. 223. 215. 196. 140.]
  [139.  93.  93.  89.  54.]
  [194. 147.  67. 249. 231.]
  [193. 181. 143. 120. 164.]]

 [[120.  93. 178. 161.  81.]
  [208. 183. 129. 227. 189.]
  [116. 119. 117.  68. 116.]
  [112.  49. 207. 168.  77.]
  [202. 169. 134.  70.  10.]]

 [[  2. 160. 112.  27. 135.]
  [131.  93. 174. 145.  65.]
  [208. 173. 115. 121.  90.]
  [ 62. 177. 163. 134. 138.]
  [129.  90. 174. 169. 103.]]]
                         30_theabductionofsita_part1
0  [[158.0, 147.0, 127.0, 210.0, 195.0], [188.0, ...
1  [[120.0, 93.0, 178.0, 161.0, 81.0], [208.0, 18...
2  [[2.0, 160.0, 112.0, 27.0, 135.0], [131.0, 93....
[[[105. 101.  28.  87.  97.]
  [ 47. 156. 125.  96. 147.]
  [110.  81. 231. 209. 149.]
  [ 85.  90.   0. 227. 192.]
  [136.  83.  38.   5. 224.]]

 [[193.  85. 218. 201. 145.]
  [ 76.  66.   7. 150. 104.]
  [ 29. 240. 176.  52. 205.]
  [174. 110. 177. 162. 139.]
  [136.  72.  11. 194. 166.]]

 [[ 59.  83.  62.  35. 207.]
  [161.  63.  26.   0.  

2  [[128.0, 186.0, 162.0, 128.0, 198.0], [207.0, ...  
[[[ 75.  89.  40.  53.  64.]
  [  4. 173. 166. 160.  76.]
  [ 86.  52. 171. 166. 163.]
  [ 93. 106.  50.  91. 101.]
  [ 40. 173. 138. 110. 111.]]

 [[ 76.  48. 215. 183. 124.]
  [220. 212. 175. 180. 126.]
  [ 54.  99.  75.  47.  77.]
  [ 68.   0. 102.  51.   6.]
  [173. 130.  38. 216. 180.]]

 [[118. 208. 143.   0.  92.]
  [ 76.  17. 116.  26.   2.]
  [ 59.  40.   0. 193. 168.]
  [101. 204. 134.   4. 139.]
  [129.  67. 237. 195. 137.]]]
                         30_theabductionofsita_part1  \
0  [[158.0, 147.0, 127.0, 210.0, 195.0], [188.0, ...   
1  [[120.0, 93.0, 178.0, 161.0, 81.0], [208.0, 18...   
2  [[2.0, 160.0, 112.0, 27.0, 135.0], [131.0, 93....   

                               30_theabductionofsita  \
0  [[105.0, 101.0, 28.0, 87.0, 97.0], [47.0, 156....   
1  [[193.0, 85.0, 218.0, 201.0, 145.0], [76.0, 66...   
2  [[59.0, 83.0, 62.0, 35.0, 207.0], [161.0, 63.0...   

                         30_theabductionofsita_part3  

2  [[88.0, 200.0, 181.0, 63.0, 174.0], [102.0, 43...  
[[[ 66.  68.  31. 188. 186.]
  [112. 188. 188. 134. 163.]
  [168. 110. 201. 187. 161.]
  [ 51.  89. 112.  39.  33.]
  [  7.  92.  92.  30. 103.]]

 [[100.  85. 147. 115.  56.]
  [ 92. 128. 150. 118. 117.]
  [ 50. 147. 146.  79. 156.]
  [119. 137. 146.  80.   2.]
  [103. 107.  74. 120. 112.]]

 [[ 63.  85.  69.  20. 146.]
  [121. 125. 146.  99.  53.]
  [162. 160.  75. 105. 110.]
  [ 30. 128.  93.  55. 133.]
  [ 95. 120. 205. 149. 112.]]]
                         30_theabductionofsita_part1  \
0  [[158.0, 147.0, 127.0, 210.0, 195.0], [188.0, ...   
1  [[120.0, 93.0, 178.0, 161.0, 81.0], [208.0, 18...   
2  [[2.0, 160.0, 112.0, 27.0, 135.0], [131.0, 93....   

                               30_theabductionofsita  \
0  [[105.0, 101.0, 28.0, 87.0, 97.0], [47.0, 156....   
1  [[193.0, 85.0, 218.0, 201.0, 145.0], [76.0, 66...   
2  [[59.0, 83.0, 62.0, 35.0, 207.0], [161.0, 63.0...   

                         30_theabductionofsita_part3  

[[[ 90.  67.  25.  95.  56.]
  [ 39. 137. 127. 118.  59.]
  [ 66.  48. 144. 133.  88.]
  [110. 101.  46.  62.  59.]
  [ 24. 183. 127.  66. 151.]]

 [[110.  46.  37.  51.  77.]
  [108.  85.  44. 149. 139.]
  [114. 127.  66.  73. 100.]
  [ 44.   9. 175. 169. 145.]
  [ 34.  20.   9. 201. 192.]]

 [[175. 159. 152. 146.  52.]
  [ 45.  37. 109.  80.  46.]
  [147. 106.  60. 170. 153.]
  [107. 143. 105.  84.  26.]
  [ 45.  26.  97.  44.  12.]]]
                         30_theabductionofsita_part1  \
0  [[158.0, 147.0, 127.0, 210.0, 195.0], [188.0, ...   
1  [[120.0, 93.0, 178.0, 161.0, 81.0], [208.0, 18...   
2  [[2.0, 160.0, 112.0, 27.0, 135.0], [131.0, 93....   

                               30_theabductionofsita  \
0  [[105.0, 101.0, 28.0, 87.0, 97.0], [47.0, 156....   
1  [[193.0, 85.0, 218.0, 201.0, 145.0], [76.0, 66...   
2  [[59.0, 83.0, 62.0, 35.0, 207.0], [161.0, 63.0...   

                         30_theabductionofsita_part3  \
0  [[56.0, 37.0, 31.0, 62.0, 47.0], [50.0, 121.0,... 

[3 rows x 24 columns]
